### ISSUE TITLE
Unable to add provable component to a existing regular rust project

### ISSUE THREAD

**Issue by azurwastaken** [succinctlabs/sp1#2096]
### Component

cargo prove CLI/sp1up

### Have you ensured that all of these are up to date?

- [x] SP1 SDK
- [x] cargo prove CLI/sp1up

### What version of SP1 SDK are you on?

4.0.0

### What version of the cargo prove CLI are you on?

cargo-prove sp1 (c97ccf2 2025-02-11T04:25:28.281688000Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hello,
I played around with the project template and everything worked fine but when I tried to add some proved computation to an existing project, I faced many dependencies issues.

The first one was the base64ct which compile in version 1.6.0 in the template program due to Cargo.lock but when its not specified i got the following error :

```
error: failed to download `base64ct v1.7.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/azur/.cargo/registry/src/index.crates.io-6f17d22bba15001f/base64ct-1.7.0/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.81.0 (2dbb1af80 2024-08-20)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
```

I managed to make it work by modifying the version in Cargo.lock manually but after this i have the following issue:

````
cargo:warning=rustc +succinct --version: "rustc 1.82.0-dev\n"
[sp1]     Compiling socket2 v0.5.8
[sp1]     Compiling mio v1.0.3
[sp1]     Compiling rand v0.8.5
[sp1]     Compiling darling_core v0.20.10
[sp1]     Compiling thiserror v1.0.69
[sp1]     Compiling object v0.36.7
[sp1]     Compiling gimli v0.31.1
[sp1]     Compiling anyhow v1.0.96
[sp1]     Compiling spin v0.9.8
[sp1]     Compiling rustc-demangle v0.1.24
[sp1]     Compiling num-iter v0.1.45
[sp1]     Compiling arrayvec v0.7.6
[sp1]  error[E0583]: file not found for module `sys`
[sp1]     --> /Users/azur/.cargo/registry/src/index.crates.io-6f17d22bba15001f/socket2-0.5.8/src/lib.rs:179:1
[sp1]      |
[sp1]  179 | mod sys;
[sp1]      | ^^^^^^^^
[sp1]      |
[sp1]      = help: to create the module `sys`, create file "/Users/azur/.cargo/registry/src/index.crates.io-6f17d22bba15001f/socket2-0.5.8/src/sys.rs" or "/Users/azur/.cargo/registry/src/index.crates.io-6f17d22bba15001f/socket2-0.5.8/src/sys/mod.rs"
[sp1]      = note: if there is a `mod sys` elsewhere in the crate already, import it with `use crate::...` instead
````

does anyone already faced this kind of problem ?

**Comment by ratankaliani** [comment]
Hey @azurwastaken, your first issue issue is related to https://github.com/succinctlabs/sp1/issues/2097. `edition2024` requires Rust `1.85`, which we just added support for with https://github.com/succinctlabs/sp1/releases/tag/v4.1.2.

Let me know if that fixes your first issue.

Your second issue arises from one of your dependencies bringing in `socket2` (which accesses a system's sockets). In the zkVM, there is no notion of "sockets", so the crate that brought in `socket2` should be removed.
